%hive(hive)
select paymentId, 
sanctionsRequestId,
sanctionsts,
paymentsystem,
paymenttimestamp,
paymentscheme,
direction,
cdtdbtind,
intrbksttldt,
intrbksttlamt,
intrbksttlccy,
counterpartyacct,
counterpartyagt,
counterpartynm,
counterpartyadr,
customernm,
customeracct,
customeragt,
customeracctid,
sanctionsmatchlist,
paymentmessage from fasterpayments.FpsSanctions ${sanctionsQuery}